name: Build & Release .NET

on:
  push:
    tags:
      - 'v*.*.*'   # Запускається тільки коли пушиш тег, наприклад v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: windows-latest
            rid: win-x64

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true -p:PublishSingleFile=true

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.rid }}
        path: ./publish/${{ matrix.rid }}

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./publish

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./publish/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
